import MPP from "../components/pages/MPP"
import Head from "next/head"
const ggipolicyscholarsprogram = () => {

  return (
    <>
      <Head>
        <title>Impact Fellowship by Global Governance Initiative</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.jpg' />
      </Head>
      <MPP />
    </>

  )
}

export default ggipolicyscholarsprogram