import Head from 'next/head';
import Image from 'next/image';
import Gallery from '../components/global/Gallery';
import Heading from '../components/global/Heading';
import Hero from '../components/global/Hero';
import Slider from '../components/home/Slider';
import { SliderData } from '../components/SliderData';
import YoutubeEmbed from '../components/global/YoutubeEmbed';
import Partners from '../components/global/Partners';
import Accordion from '../components/global/Accordian';
import Socials from '../components/global/Socials';
//---------------------------------------------------------
import poets from '../public/poets.jpg';
import BCG from '../public/bcg.jpg';
import Linkedin from '../public/linkedin.jpg';
import yrstory from '../public/yrstory.jpg';
// -------------------------------------------------------
import harvardcase from '../public/harvardcase.jpg'
import becomepart from '../public/becomepart.jpg'
import leadingpurpose from '../public/leadingwithpurpose.jpg'
import officeofcareer from '../public/officeofcareer.jpg'
// -------------------------------------------------------
import bhaskar_chakra from '../public/bhaskar_chakra.jpg'
import Community from '../components/global/Community';
// -------------------------------------------------------


export default function Home() {
  return (
    <div>
      <Head>
        <title>Global Governance Initiative | MBA & Fellowship</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.jpg' />
      </Head>

      <Hero heading='' message='' />

      <div id='' className='p-4 flex justify-center'>
        <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-12 py-5 px-12 border border-blue-500 rounded">
          Learn More about Advancing Your Career
        </button>
      </div>

      <Heading heading={"Hear what GGIians who have witnessed a +200% Increase in their Salary- have to say about us"} />
      <Slider slides={SliderData} />

      <Heading heading={"+88% GGIians working in Top Consulting, Policy, Product Roles and Organizations"} />
      <Partners />


      <Heading heading={"GGI Offers Live Upskilling, Employment & Networking "} />
      <div id='' className='flex justify-center my-12'>
        <p className='px-4 md:w-4/6'>Find below specific programs within the fellowship and the 2 flagship Scholar tracks, to learn more about admission requirements, scholarships, and career opportunities and upskill on how to build a career in management consulting, product management, policy, finance, impact investing, or program management roles.    </p>
      </div>
      <div className="p-8 flex justify-center skin">
        <div className="lg:w-4/5 grid grid-cols-1 md:grid-cols-2 gap-2 lg:gap-10">
          <div>
            <h2 className='text-2xl my-8'>GGI MBA Scholar </h2>
            <p className='my-5 text-xl'>Who is this program for?</p>
            <p className='my-5'>1. You are looking for best Alternative to International- MBA</p>
            <p className='my-5'>2. You are looking to pivot in strategy and consulting roles such as Mckinsey, BCG, or Product Management</p>
            <p className='my-5'>3. You are a Pre-MBA looking to finish the business curriculum before your program</p>
            <p className='my-5'>4. You are a budding entrepreneur who is aiming to launch & scale ventures </p>
            <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-10 py-2 px-4 border border-blue-500 rounded">
              Learn More about GGI Impact MBA
            </button>
          </div>
          <div>
            <h2 className='text-2xl my-8'>GGI Policy Scholar </h2>
            <p className='my-5 text-xl'>Who is this program for?</p>
            <p className='my-5'>1. You are looking for best Alternative to International- MPP</p>
            <p className='my-5'>2. You are looking to pivot in impact firms such as UN, World Bank, FSG, or social impact roles</p>
            <p className='my-5'>3. You are a Pre-MPP with MPP admits to Harvard Kennedy, Oxford MPP, and other top MPPs</p>
            <p className='my-5'>4. You are a budding social impact entrepreneur who is aiming to launch a venture  </p>
            <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-10 py-2 px-5 border border-blue-500 rounded">
              Learn More about GGI Policy Scholar
            </button>
          </div>

        </div>
      </div>
      <div id='' className='p-4 flex justify-center'>
        <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-12 py-5 px-12 border border-blue-500 rounded">
          Learn More about Advancing Your Career
        </button>
      </div>



      <Heading heading={"You Solve Cases & Network with World's Top CEOs, Partners, Consulting, Policy, Product Leaders "} />
      <Gallery />


      <div className='mt-24 flex justify-center'>
        <p className='md:w-3/5 text-center'>Many large employers find that Global Governance Initiative prepares Young Professionals not only for General Management Positions but also for jobs within governmental affairs, environmental affairs, other functional areas that necessitate an education that goes beyond traditional business skills. </p>
      </div>
      {/* <YoutubeEmbed embedId="rokGy0huYEA" /> */}



      <Heading heading={"Global Recognition Allows us to Serve you Better"} />
      <div className="p-3 md:p-12 flex justify-center">
        <div className=" grid grid-cols-2 md:grid-cols-4 gap-4 lg:gap-5">
          <div className='flex flex-col text-center'>
            <div> <Image className='' src={poets} /></div>
            <p className='mt-3 '>"In Just 3 Years, This Disruptive Indian Pre-MBA Has Graduated 5,500 Alumni"</p>
            <p className='mt-10'>— YOURSTORY</p>
          </div>
          <div className='flex flex-col text-center'>
            <div> <Image src={BCG} /></div>
            <p className='mt-1'>"Shatakshi Sharma, a BCG Senior Associate, founded the Global Governance Initiative with the goal of providing education and careeradvancement opportunities for Indian youth"</p>
            <p className='mt-10'>— BCG Global Media</p>
          </div>
          <div className='flex flex-col text-center'>
            <div><Image className='' src={Linkedin} /></div>
            <p className='mt-10'>"Shatakshi Sharma, Cofounder, Global Governance Initiative recognized as Linkedin Top Voice, Next Gen for work on gender equality, higher education and management consulting.</p>
            <p className='mt-10'> — Linkedin News</p>
          </div>
          <div className='flex flex-col text-center'>
            <div><Image src={yrstory} /></div>
            <p className='mt-6 '>“The founders felt that with the right information and awareness, others like them, mostly youth, could also pursue jobs in public policy, and hence founded GGI.” </p>
            <p className='mt-10'> — YourStory</p>
          </div>
        </div>
      </div>


      <Heading heading={"You Learn live via Case method, Get Hired & Network to become a Leader in Business & Society"} />
      <div className="p-3 md:p-12 flex justify-center">
        <div className="md:w-4/5 grid grid-cols-2 md:grid-cols-4 gap-1 lg:gap-5">
          <div className='flex flex-col text-center'>
            <div> <Image className='' src={harvardcase} /></div>
            <h2 className='text-3xl my-8'>Harvard Case Method</h2>
            <p className='mt-3 '>Driven by experiential learning through real case based teaching and heavily interactive & live feedback based problem solving </p>
          </div>
          <div className='flex flex-col text-center'>
            <div> <Image src={officeofcareer} /></div>
            <h2 className='text-3xl my-8'>Office of  Career Service</h2>
            <p className='mt-1'>GGI facilitates your hiring by partnering with leading employment partners in consulting, & PM along with resume' and interview prep</p>
          </div>
          <div className='flex flex-col text-center'>
            <div><Image className='' src={becomepart} /></div>
            <h2 className='text-3xl my-8'>Become part of the Tribe</h2>
            <p className='mt-10'>Masterclasses are designed to ensure your peer to peer-based learning; so that you grow by growing others. </p>
          </div>
          <div className='flex flex-col text-center'>
            <div><Image src={leadingpurpose} /></div>
            <h2 className='text-3xl my-8'>Leading with Purpose </h2>
            <p className='mt-6 '>All GGI Masterclasses are curated with a sharp focus on responsible capitalism and ethics by involving leaders, not managers </p>
          </div>
        </div>
      </div>
      <div id='' className='p-4 flex justify-center'>
        <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-12 py-5 px-12 border border-blue-500 rounded">
          Learn More about GGI Impact MBA Scholars
        </button>
      </div>

      <Heading heading={"At GGI, We Believe In-Person Community is the CornerStone when You are Learning Online"} />
      <Community/>

      <div id='' className='p-4 flex justify-center mb-60'>
        <button className="bg-blue-700 hover:bg-blue-500 text-white font-bold my-12 py-5 px-12 border border-blue-500 rounded">
          Learn More about GGI Impact MBA Scholars
        </button>
      </div>
      <div className="flex justify-center">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-1">
          <div className='col-span-2'><Image src={bhaskar_chakra} /></div>
          <div className='flex flex-col justify-center content-center gap-7 p-10 col-span-1'>
            <p className='text-3xl tracking-widest font-extrabold'>GGI Advisor</p>
            <p className='text-xl'>Bhaskar Chakravorti</p>
            <p className='mt-3'>Mr. Bhaskar brings decades of experience having worked as former Partner- McKinsey & Co., Dean of Global business- The Fletcher School, Faculty- Harvard Business School, Advisor- World Economic Forum, UNDP, Brookings Institution, and MasterCard</p>
          </div>
        </div>
      </div>


      <Heading heading={"Cofounder's Desk"} />
      <Heading heading={"Frequently Asked Questions"} />
      <Accordion />

      <Socials/>

    </div>
  );
}
