import Head from 'next/head';
import Image from 'next/image';
import Gallery from '../components/Gallery';
import Heading from '../components/Heading';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Testimonial from '../components/Testimonial';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Global Governance Initiative | MBA & Fellowship</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.jpg' />
      </Head>

      <Hero heading='' message='' />

      <div id='' className='flex justify-center'>
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 border border-blue-700 rounded">
          Learn More about Advancing Your Career
        </button>
      </div>

      <Heading heading={"Hear what GGIians who have witnessed a +200% Increase in their Salary- have to say about us"} />
      <Slider slides={SliderData} />

      <Heading heading={"+88% GGIians working in Top Consulting, Policy, Product Roles and Organizations"} />
      <Instagram />



      <Heading heading={"GGI Offers Live Upskilling, Employment & Networking "} />
      <div id='' className='flex justify-center my-12'>
        <p className='px-4 md:w-4/6'>Find below specific programs within the fellowship and the 2 flagship Scholar tracks, to learn more about admission requirements, scholarships, and career opportunities and upskill on how to build a career in management consulting, product management, policy, finance, impact investing, or program management roles.    </p>
      </div>
      <div className="p-8 flex justify-center">
        <div className="lg:w-4/5 grid grid-cols-1 md:grid-cols-2 gap-2 lg:gap-10">
          <div>
            <h2 className='text-2xl my-8'>GGI MBA Scholar </h2>
            <p className='my-5 text-xl'>Who is this program for?</p>
            <p className='my-5'>1. You are looking for best Alternative to International- MBA</p>
            <p className='my-5'>2. You are looking to pivot in strategy and consulting roles such as Mckinsey, BCG, or Product Management</p>
            <p className='my-5'>3. You are a Pre-MBA looking to finish the business curriculum before your program</p>
            <p className='my-5'>4. You are a budding entrepreneur who is aiming to launch & scale ventures </p>
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold my-10 py-2 px-4 border border-blue-700 rounded">
              Learn More about GGI Impact MBA
            </button>
          </div>
          <div>
            <h2 className='text-2xl my-8'>GGI Policy Scholar </h2>
            <p className='my-5 text-xl'>Who is this program for?</p>
            <p className='my-5'>1. You are looking for best Alternative to International- MPP</p>
            <p className='my-5'>2. You are looking to pivot in impact firms such as UN, World Bank, FSG, or social impact roles</p>
            <p className='my-5'>3. You are a Pre-MPP with MPP admits to Harvard Kennedy, Oxford MPP, and other top MPPs</p>
            <p className='my-5'>4. You are a budding social impact entrepreneur who is aiming to launch a venture  </p>
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold my-10 py-2 px-4 border border-blue-700 rounded">
              Learn More about GGI Policy Scholar
            </button>
          </div>

        </div>
      </div>
      <div id='' className='flex justify-center'>
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold my-12 py-3 px-4 border border-blue-700 rounded">
          Learn More about Advancing Your Career
        </button>
      </div>



      <Heading heading={"You Solve Cases & Network with World's Top CEOs, Partners, Consulting, Policy, Product Leaders "} />
      <Gallery />

      <Heading heading={"Global Recognition Allows us to Serve you Better"} />

      <Heading heading={"You Learn live via Case method, Get Hired & Network to become a Leader in Business & Society"} />
      <Heading heading={"At GGI, We Believe In-Person Community is the CornerStone when You are Learning Online"} />
      <Heading heading={"Cofounder's Desk"} />
      <Heading heading={"Frequently Asked Questions"} />
    </div>
  );
}
